#cloud-config

ssh_authorized_keys:
  - %(LOCAL_SSH_KEY)s

# Launch instance with network interfaces configured to the local IP addresses we references in the config.
# $ aws ec2 run-instances --user-data file://check-files.yml --iam-instance-profile Name="encoded-instance" --image-id ami-5a928a3b --region us-west-2 --security-groups ssh-http-https --instance-type c4.xlarge

output:
  all: '| tee -a /var/log/cloud-init-output.log'

packages:
- fuse
## - golang
- git
- curl
- ntp
- python-pip
- python3-dev
- python3-venv

## power_state:
##   mode: poweroff

runcmd:
- set -ex
- pip install awscli
- sudo -u ubuntu mv /home/ubuntu/.ssh/authorized_keys /home/ubuntu/.ssh/authorized_keys2
- sudo -u ubuntu aws s3 cp --region=us-west-2 %(S3_AUTH_KEYS)s /home/ubuntu/.ssh/authorized_keys
- systemctl daemon-reload  # See https://bugs.launchpad.net/cloud-init/+bug/1449318
- mkdir -p /s3/encode-files
- mkdir -p /s3/encoded-files-dev
- mkdir -p /s3/encode-private
- mkdir -p /s3/encode-public

- curl -sS -L -o /usr/local/bin/goofys https://github.com/kahing/goofys/releases/download/v0.23.1/goofys
- chmod +x /usr/local/bin/goofys

## - mkdir -p /opt/goofys/bin
## - chown -R build:build /opt/goofys
## - sudo -u build GOPATH=/opt/goofys go get github.com/kahing/goofys
## - mv /opt/goofys/bin/goofys /usr/local/bin/

- mount -a

- mkdir /opt/encValData
- chown build:build /opt/encValData
- sudo -u build git clone --depth 1 https://github.com/ENCODE-DCC/encValData /opt/encValData

- curl -sS -L -o /usr/local/bin/validateFiles http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/validateFiles
- chmod +x /usr/local/bin/validateFiles

- mkdir /opt/encoded
- chown build:build /opt/encoded
- mkdir /opt/encoded/checkfiles
- chown build:build /opt/encoded/checkfiles
- sudo -u build git clone --no-checkout https://github.com/ENCODE-DCC/checkfiles.git /opt/encoded/checkfiles
- sudo -u build git -C /opt/encoded/checkfiles checkout %(COMMIT)s
- chmod +x /opt/encoded/checkfiles/script

- cd /opt/encoded/checkfiles
- sudo -u build pyvenv .
- sudo -u build bin/pip install -r requirements.txt 

- cd /home/ubuntu
- nohup /opt/encoded/checkfiles/script $(cat /opt/checkfiles_args.txt) 2> errors.log 1> output.log &
- cut -d " " -f 1-6 /opt/checkfiles_args.txt > /opt/test_args.txt 
- echo "$(cat /opt/test_args.txt) https://test.encodedcc.org" > /opt/test_args.txt
- nohup /opt/encoded/checkfiles/script "$(cat /opt/test_args.txt)" 2> errors_test.log 1> output_test.log &

users:
- default
- name: build
  gecos: Build user
  inactive: true
  system: true

mounts:
- [ "goofys-ulimit#encode-files", "/s3/encode-files", "fuse", "_netdev,allow_other,--file-mode=0444,--dir-mode=0555,--stat-cache-ttl=0", "0", "0" ]
- [ "goofys-ulimit#encoded-files-dev", "/s3/encoded-files-dev", "fuse", "_netdev,allow_other,--file-mode=0444,--dir-mode=0555,--stat-cache-ttl=0", "0", "0" ]
- [ "goofys-ulimit#encode-private", "/s3/encode-private", "fuse", "_netdev,allow_other,--file-mode=0444,--dir-mode=0555,--stat-cache-ttl=0", "0", "0" ]
- [ "goofys-ulimit#encode-public", "/s3/encode-public", "fuse", "_netdev,allow_other,--file-mode=0444,--dir-mode=0555,--stat-cache-ttl=0", "0", "0" ]

write_files:
- path: /opt/checkfiles_args.txt
  content: |
    %(ARGS)s
- path: /etc/systemd/system/cloud-final.service.d/override.conf
  content: |
    [Service]
    # See https://bugs.launchpad.net/cloud-init/+bug/1449318
    KillMode=process
- path: /usr/local/bin/goofys-ulimit
  permissions: 0755
  content: |
    #!/bin/sh
    ulimit -n 60000
    exec goofys "$@"
- path: /etc/rc.local
  permissions: 0755
  content: |
    #!/bin/sh -e
    cd /home/ubuntu; nohup /opt/encoded/checkfiles/script %(ARGS)s 2> errors.log 1> output.log &; nohup /opt/encoded/checkfiles/script "$(cat /opt/test_args.txt)" 2> errors.log 1> output.log &;  
    exit 0
