#!/bin/bash
while :
    do
        now=$(date +"%Y%m%d%H%M%S")
        /opt/encoded/checkfiles/bin/python /opt/encoded/checkfiles/checkfiles.py "$@" --out $now-checkfiles.log --err $now-checkfiles-error.log --include-unexpired-upload 2> $now-file-errors.log 1> $now-file-output.log
        /opt/encoded/checkfiles/bin/python /opt/encoded/checkfiles/checkexperiments.py "$@" --out $now-checkexperiments.log --err $now-checkexperiments-error.log 2> $now-exp-errors.log 1> $now-exp-output.log
        /opt/encoded/checkfiles/bin/python /opt/encoded/checkfiles/checkmd5.py "$@" --out $now-checkmd5.log --err $now-checkmd5-error.log 2> $now-md5-errors.log 1> $now-md5-output.log
        sleep 480m
done